package com.class_design.constructor;

public class ConstructorDemo {
    /*
        - Special methods that are executed when an instance of a class is created
        - name of the constructor must match the name of the class
        - constructors don't have a return type
            - if return type is stated, then it's a normal method

         - default constructor is created only if no other constructor is present

       Constructor Access Modifiers
         - Constructors are usually made public
             they can also be made private default or protected
         - private constructors are used if you don't want a public no-arg constructor to be
            generated by the compiler
            - in this case the object is generally created via a static method, not using the 'new' keyword

        special method this() is used to call another constructor in a constructor
            - this() can be called in teh first line in the constructor
            - this() can be called only once
            - care should be taken as to not create a cycle (circular constructors)

        special method super() is used to call a constructor of a superclass in a constructor of the subclass
            - if there is no this() or super() in the first line
                then compiler will automatically insert super()
     */
}
